#!/bin/bash
# Generate runtime config for frontend
# Only set API_BASE_URL if explicitly provided, otherwise use same-origin (no CORS)
if [ -n "$API_BASE_URL" ]; then
  cat > /app/server/public/config.js << EOF
// Runtime configuration generated by Docker startup script
window.API_BASE_URL = '${API_BASE_URL}';
EOF
  echo "Generated config.js with API_BASE_URL=${API_BASE_URL}"
else
  cat > /app/server/public/config.js << EOF
// Runtime configuration generated by Docker startup script
// No API_BASE_URL set - using same origin (proxied via nginx)
EOF
  echo "Generated config.js with same-origin API calls"
fi
