all:
  hosts:
    pi:
      ansible_ssh_port: 22
      ansible_become_method: sudo
      ansible_connection: ssh
      ansible_host: "192.168.0.4"
      ansible_user: "sulai"
      target_platform: "linux/arm64"
  vars:
    talktogether_build_context: "{{ playbook_dir }}/../../.."
    db_name: talktogether
    db_user: postgres
    db_password: your_db_password
    db_host: 192.168.0.4
    db_port: 5432
    api_base_url: "https://talktogether.sascha-wernegger.me/api/"
    node_port: 3000
